/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import javax.swing.JOptionPane;

/**
 *
 * @author Ephraim
 */
public class HomeForm extends javax.swing.JFrame {

    private final String hm_fn, hm_uid;

    /**
     * Creates new form HomeForm
     *
     * @param hm_fn
     * @param hm_uid
     */
    public HomeForm(String hm_fn, String hm_uid) {
        initComponents();
        this.hm_fn = hm_fn;
        this.hm_uid = hm_uid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hm_img = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hm_display_msg = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        hm_title = new javax.swing.JLabel();
        hm_user_email = new javax.swing.JLabel();
        hm_user_fullname = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        hm_home_item = new javax.swing.JMenu();
        hm_msg_menu = new javax.swing.JMenu();
        hm_send_msg = new javax.swing.JMenuItem();
        hm_view_msg = new javax.swing.JMenuItem();
        hm_view_msg2 = new javax.swing.JMenuItem();
        hm_actions = new javax.swing.JMenu();
        hm_logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secured Desktop Messaging System");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(196, 223, 244));

        hm_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tips.jpg"))); // NOI18N

        hm_display_msg.setEditable(false);
        hm_display_msg.setBackground(new java.awt.Color(196, 223, 244));
        hm_display_msg.setBorder(null);
        hm_display_msg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hm_display_msg.setText("This platform allow users to send and recieve encrypted messages using the Advanced Encryption Encryption Standard (AES) algorithm");
        jScrollPane1.setViewportView(hm_display_msg);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hm_img, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hm_img)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(13, 20, 28));

        hm_title.setBackground(new java.awt.Color(13, 20, 28));
        hm_title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hm_title.setForeground(new java.awt.Color(255, 255, 255));
        hm_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hm_title.setText("Secured Desktop Based Messaging System");

        hm_user_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hm_user_email.setForeground(new java.awt.Color(255, 255, 255));
        hm_user_email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hm_user_email.setText("email");

        hm_user_fullname.setForeground(new java.awt.Color(255, 255, 255));
        hm_user_fullname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hm_user_fullname.setText("fullname");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(hm_title, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hm_user_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hm_user_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hm_title, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hm_user_email, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hm_user_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );

        jPanel3.setBackground(new java.awt.Color(13, 20, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Secured Desktop Messaging System. 2021 All Rights Reserved.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        hm_home_item.setText("Home");
        hm_home_item.setToolTipText("");
        hm_home_item.setEnabled(false);
        hm_home_item.setMargin(new java.awt.Insets(5, 2, 5, 2));
        jMenuBar1.add(hm_home_item);

        hm_msg_menu.setText("Messages");
        hm_msg_menu.setMargin(new java.awt.Insets(5, 0, 5, 0));

        hm_send_msg.setText("Send Message");
        hm_send_msg.setMargin(new java.awt.Insets(5, 0, 5, 0));
        hm_send_msg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hm_send_msgMouseClicked(evt);
            }
        });
        hm_send_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hm_send_msgActionPerformed(evt);
            }
        });
        hm_msg_menu.add(hm_send_msg);

        hm_view_msg.setText("Inbox Messages");
        hm_view_msg.setMargin(new java.awt.Insets(5, 0, 5, 0));
        hm_view_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hm_view_msgActionPerformed(evt);
            }
        });
        hm_msg_menu.add(hm_view_msg);

        hm_view_msg2.setText("Outbox Messages");
        hm_view_msg2.setMargin(new java.awt.Insets(5, 0, 5, 0));
        hm_view_msg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hm_view_msg2ActionPerformed(evt);
            }
        });
        hm_msg_menu.add(hm_view_msg2);

        jMenuBar1.add(hm_msg_menu);

        hm_actions.setText("Actions");
        hm_actions.setMargin(new java.awt.Insets(5, 2, 5, 0));
        hm_actions.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                hm_actionsMenuSelected(evt);
            }
        });
        hm_actions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hm_actionsMouseClicked(evt);
            }
        });

        hm_logout.setText("Logout");
        hm_logout.setMargin(new java.awt.Insets(5, 0, 5, 0));
        hm_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hm_logoutActionPerformed(evt);
            }
        });
        hm_actions.add(hm_logout);

        jMenuBar1.add(hm_actions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        hm_user_email.setText(hm_uid);
        hm_user_fullname.setText(hm_fn);
    }//GEN-LAST:event_formWindowOpened

    private void hm_actionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hm_actionsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hm_actionsMouseClicked

    private void hm_send_msgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hm_send_msgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hm_send_msgMouseClicked

    private void hm_actionsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_hm_actionsMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_hm_actionsMenuSelected

    private void hm_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hm_logoutActionPerformed
        // TODO add your handling code here:
        int exit_answer = JOptionPane.showConfirmDialog(this, "Are you sure to "
                + "logout?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (exit_answer == 0) {
            LoginForm lf = new LoginForm();
            lf.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_hm_logoutActionPerformed

    private void hm_send_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hm_send_msgActionPerformed
        // TODO add your handling code here:
        String[] args = {hm_uid, hm_fn};
        SendMessageForm.main(args);
        this.dispose();
    }//GEN-LAST:event_hm_send_msgActionPerformed

    private void hm_view_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hm_view_msgActionPerformed
        // TODO add your handling code here:
        String[] args = {hm_uid, hm_fn};
        InboxMessages.main(args);
        this.dispose();
    }//GEN-LAST:event_hm_view_msgActionPerformed

    private void hm_view_msg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hm_view_msg2ActionPerformed
        // TODO add your handling code here:
        String[] args = {hm_uid, hm_fn};
        OutboxMessages.main(args);
        this.dispose();
    }//GEN-LAST:event_hm_view_msg2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm(args[1], args[0]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu hm_actions;
    private javax.swing.JTextPane hm_display_msg;
    private javax.swing.JMenu hm_home_item;
    private javax.swing.JLabel hm_img;
    private javax.swing.JMenuItem hm_logout;
    private javax.swing.JMenu hm_msg_menu;
    private javax.swing.JMenuItem hm_send_msg;
    private javax.swing.JLabel hm_title;
    private javax.swing.JLabel hm_user_email;
    private javax.swing.JLabel hm_user_fullname;
    private javax.swing.JMenuItem hm_view_msg;
    private javax.swing.JMenuItem hm_view_msg2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
