/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import resources.AlgorithmAES;
import resources.ConnectDB;

/**
 *
 * @author Ephraim
 */
public class Message extends javax.swing.JFrame {

    private final String hm_uid, hm_fn, msgid;

    /**
     * Creates new form Message
     *
     * @param hm_fn
     * @param hm_uid
     * @param msgid
     */
    public Message(String hm_fn, String hm_uid, String msgid) {
        initComponents();
        this.hm_fn = hm_fn;
        this.hm_uid = hm_uid;
        this.msgid = msgid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        msg_from = new javax.swing.JTextField();
        msg_to = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        act_msg = new javax.swing.JTextPane();
        decrypt_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        hm_home_item = new javax.swing.JMenu();
        hm_msg_menu = new javax.swing.JMenu();
        hm_send_msg = new javax.swing.JMenuItem();
        hm_view_msg = new javax.swing.JMenuItem();
        hm_view_msg2 = new javax.swing.JMenuItem();
        hm_actions = new javax.swing.JMenu();
        hm_logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secured Desktop Messaging System");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(13, 20, 28));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Message");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(13, 20, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Secured Desktop Messaging System. 2021 All Rights Reserved.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("From:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("To");

        msg_from.setEditable(false);

        msg_to.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Message:");

        act_msg.setEditable(false);
        jScrollPane1.setViewportView(act_msg);

        decrypt_btn.setBackground(new java.awt.Color(36, 38, 123));
        decrypt_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        decrypt_btn.setForeground(new java.awt.Color(255, 255, 255));
        decrypt_btn.setText("Decrypt Message");
        decrypt_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decrypt_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(decrypt_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(msg_to))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(msg_from)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(msg_from, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(msg_to, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decrypt_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        hm_home_item.setText("Home");
        hm_home_item.setToolTipText("");
        hm_home_item.setMargin(new java.awt.Insets(5, 2, 5, 2));
        hm_home_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hm_home_itemMouseClicked(evt);
            }
        });
        jMenuBar1.add(hm_home_item);

        hm_msg_menu.setText("Messages");
        hm_msg_menu.setMargin(new java.awt.Insets(5, 0, 5, 0));

        hm_send_msg.setText("Send Message");
        hm_send_msg.setMargin(new java.awt.Insets(5, 0, 5, 0));
        hm_send_msg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hm_send_msgMouseClicked(evt);
            }
        });
        hm_send_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hm_send_msgActionPerformed(evt);
            }
        });
        hm_msg_menu.add(hm_send_msg);

        hm_view_msg.setText("Inbox Messages");
        hm_view_msg.setMargin(new java.awt.Insets(5, 0, 5, 0));
        hm_view_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hm_view_msgActionPerformed(evt);
            }
        });
        hm_msg_menu.add(hm_view_msg);

        hm_view_msg2.setText("Outbox Messages");
        hm_view_msg2.setMargin(new java.awt.Insets(5, 0, 5, 0));
        hm_view_msg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hm_view_msg2ActionPerformed(evt);
            }
        });
        hm_msg_menu.add(hm_view_msg2);

        jMenuBar1.add(hm_msg_menu);

        hm_actions.setText("Actions");
        hm_actions.setMargin(new java.awt.Insets(5, 2, 5, 0));
        hm_actions.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                hm_actionsMenuSelected(evt);
            }
        });
        hm_actions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hm_actionsMouseClicked(evt);
            }
        });

        hm_logout.setText("Logout");
        hm_logout.setMargin(new java.awt.Insets(5, 0, 5, 0));
        hm_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hm_logoutActionPerformed(evt);
            }
        });
        hm_actions.add(hm_logout);

        jMenuBar1.add(hm_actions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hm_home_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hm_home_itemMouseClicked
        // TODO add your handling code here:
        String[] args = {hm_uid, hm_fn};
        HomeForm.main(args);
        this.dispose();
    }//GEN-LAST:event_hm_home_itemMouseClicked

    private void hm_send_msgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hm_send_msgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hm_send_msgMouseClicked

    private void hm_send_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hm_send_msgActionPerformed
        // TODO add your handling code here:
        String[] args = {hm_uid, hm_fn};
        SendMessageForm.main(args);
        this.dispose();
    }//GEN-LAST:event_hm_send_msgActionPerformed

    private void hm_view_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hm_view_msgActionPerformed
        // TODO add your handling code here:
        String[] args = {hm_uid, hm_fn};
        InboxMessages.main(args);
        this.dispose();
    }//GEN-LAST:event_hm_view_msgActionPerformed

    private void hm_view_msg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hm_view_msg2ActionPerformed
        // TODO add your handling code here:
        String[] args = {hm_uid, hm_fn};
        OutboxMessages.main(args);
        this.dispose();
    }//GEN-LAST:event_hm_view_msg2ActionPerformed

    private void hm_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hm_logoutActionPerformed
        // TODO add your handling code here:
        int exit_answer = JOptionPane.showConfirmDialog(this, "Are you sure to "
                + "logout?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (exit_answer == 0) {
            LoginForm lf = new LoginForm();
            lf.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_hm_logoutActionPerformed

    private void hm_actionsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_hm_actionsMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_hm_actionsMenuSelected

    private void hm_actionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hm_actionsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hm_actionsMouseClicked

    private void markAsRead(String msgID) {
        try {
            ConnectDB connDB = new ConnectDB();
            Connection conn = connDB.getConnection();
            String msg_tbl = connDB.MESSAGES_TABLE;
            String query = "UPDATE " + msg_tbl + " SET read_status = ? WHERE msg_id = ?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, "read");
            ps.setString(2, msgID);
            ps.executeUpdate();
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private ResultSet getSingleMessage(String msgID) {
        try {
            ResultSet result = null;
            ConnectDB connDB = new ConnectDB();
            Connection conn = connDB.getConnection();
            String msg_tbl = connDB.MESSAGES_TABLE;
            String query = "SELECT * FROM " + msg_tbl + " WHERE msg_id=?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, msgID);
            ResultSet rs = ps.executeQuery();
            result = rs;
            return result;
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return null;
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            //ResultSet rs = getSingleMessage(msgid);

            ConnectDB connDB = new ConnectDB();
            Connection conn = connDB.getConnection();
            String msg_tbl = connDB.MESSAGES_TABLE;
            String query = "SELECT * FROM " + msg_tbl + " WHERE msg_id=?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, msgid);
            ResultSet rs = ps.executeQuery();
            rs.next();
            
            String t_msg_from = rs.getString("sender");
            String t_msg_to = rs.getString("reciever");
            String msg_text = rs.getString("msg_text");

            if (hm_uid.equalsIgnoreCase(t_msg_from)) {
                t_msg_from = "Me";
            }

            if (hm_uid.equalsIgnoreCase(t_msg_to)) {
                t_msg_to = "Me";
            }

            msg_from.setText(t_msg_from); //display from
            msg_to.setText(t_msg_to); //didsplay to
            act_msg.setText(msg_text); //display message on text pane

            if ("locked".equalsIgnoreCase(rs.getString("decrypt_status"))) {
                decrypt_btn.setEnabled(true);
            } else {
                decrypt_btn.setEnabled(false);
            }
            
            conn.close();

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    //private void markUnlocked(String msgID, String decrypted_msg_text) {
    private void markUnlocked(String msgID) {
        try {
            ConnectDB connDB = new ConnectDB();
            Connection conn = connDB.getConnection();
            String msg_tbl = connDB.MESSAGES_TABLE;
            String query = "UPDATE " + msg_tbl + " SET decrypt_status = ? WHERE msg_id = ?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, "unlocked");
            ps.setString(2, msgID);
            ps.executeUpdate();
            conn.close();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void decrypt_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decrypt_btnMouseClicked
        // TODO add your handling code here:
        try {
            ResultSet rs = getSingleMessage(msgid);
            AlgorithmAES aes = new AlgorithmAES(rs.getString("msg_text"));
            String decrypt_msg = aes.decryptMessage(rs.getString("secret_key"));
            //this.markUnlocked(msgid);
            act_msg.setText(decrypt_msg);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_decrypt_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Message(args[1], args[0], args[2]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane act_msg;
    private javax.swing.JButton decrypt_btn;
    private javax.swing.JMenu hm_actions;
    private javax.swing.JMenu hm_home_item;
    private javax.swing.JMenuItem hm_logout;
    private javax.swing.JMenu hm_msg_menu;
    private javax.swing.JMenuItem hm_send_msg;
    private javax.swing.JMenuItem hm_view_msg;
    private javax.swing.JMenuItem hm_view_msg2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField msg_from;
    private javax.swing.JTextField msg_to;
    // End of variables declaration//GEN-END:variables
}
